export abstract class ResourceName {

    public static readonly PHYSICAL_ACTIVITIES: string = 'physicalactivities.find'
    public static readonly SLEEP: string = 'sleep.find'
    public static readonly WEIGHTS: string = 'weights.find'
    public static readonly ENVIRONMENTS: string = 'environments.find'
    public static readonly LOGS: string = 'logs.find'
    public static readonly CHILDREN: string = 'children.find'
    public static readonly FAMILIES: string = 'families.find'
    public static readonly FAMILY_CHILDREN: string = 'familychildren.find'
    public static readonly EDUCATORS: string = 'educators.find'
    public static readonly EDUCATORS_CHILDRES_GROUPS: string = 'educators.childrengroups'
    public static readonly HEALTH_PROFESSIONALS: string = 'healthprofessionals.find'
    public static readonly HEALTH_PROFESSIONAL_CHILDREN_GROUPS: string = 'healthprofessionals.childrengroups'
    public static readonly APPLICATIONS: string = 'applications.find'
    public static readonly INSTITUTIONS: string = 'institutions.find'
    public static readonly CHILD_FROM_EDUCATOR: string = 'child.educators.find'
    public static readonly CHILD_FROM_HEALTH_PROFESSIONAL: string = 'child.healthprofessionals.find'
    public static readonly FOODS: string = 'foods.find'
}
